### ISSUE TITLE
How would this be used with a "Basic Query"?

### ISSUE THREAD

**Issue by mikful** [ntivirikin/xeno-canto-py#1]
Hi, thanks for this code. I'm wondering how it would be used with a basic query for the species as well as the advanced queries?, e.g.:

xenocanto.get_rec(['Oxyura jamaicensis','cnt:Colombia','q>:D'])

This throws an error:

`---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
<ipython-input-46-3f373a424fde> in <module>
     18     # Country: Colombia, quality > class D (A-C)
     19     print(str(i))
---> 20 xenocanto.get_rec(['Oxyura jamaicensis','cnt:Colombia','q>:D'])

~/anaconda3/lib/python3.7/site-packages/xenocanto.py in get_rec(search)
    123 # Combines get_json and get_mp3 for convenience
    124 def get_rec(search):
--> 125     json_list = get_json(search)
    126     mp3_list = get_mp3(json_list)
    127 

~/anaconda3/lib/python3.7/site-packages/xenocanto.py in get_json(search)
     47     url = url_builder(search)
     48     try:
---> 49         r = request.urlopen(url)
     50     except error.HTTPError as e:
     51         err_log(e)

~/anaconda3/lib/python3.7/urllib/request.py in urlopen(url, data, timeout, cafile, capath, cadefault, context)
    220     else:
    221         opener = _opener
--> 222     return opener.open(url, data, timeout)
    223 
    224 def install_opener(opener):

~/anaconda3/lib/python3.7/urllib/request.py in open(self, fullurl, data, timeout)
    529         for processor in self.process_response.get(protocol, []):
    530             meth = getattr(processor, meth_name)
--> 531             response = meth(req, response)
    532 
    533         return response

~/anaconda3/lib/python3.7/urllib/request.py in http_response(self, request, response)
    639         if not (200 <= code < 300):
    640             response = self.parent.error(
--> 641                 'http', request, response, code, msg, hdrs)
    642 
    643         return response

~/anaconda3/lib/python3.7/urllib/request.py in error(self, proto, *args)
    567         if http_err:
    568             args = (dict, 'default', 'http_error_default') + orig_args
--> 569             return self._call_chain(*args)
    570 
    571 # XXX probably also want an abstract factory that knows when it makes

~/anaconda3/lib/python3.7/urllib/request.py in _call_chain(self, chain, kind, meth_name, *args)
    501         for handler in handlers:
    502             func = getattr(handler, meth_name)
--> 503             result = func(*args)
    504             if result is not None:
    505                 return result

~/anaconda3/lib/python3.7/urllib/request.py in http_error_default(self, req, fp, code, msg, hdrs)
    647 class HTTPDefaultErrorHandler(BaseHandler):
    648     def http_error_default(self, req, fp, code, msg, hdrs):
--> 649         raise HTTPError(req.full_url, code, msg, hdrs, fp)
    650 
    651 class HTTPRedirectHandler(BaseHandler):

HTTPError: HTTP Error 400: Bad Request'`

**Comment by tctree333** [comment]
You'll need to URL encode it and place your search terms in the same string:
`xenocanto.get_rec(["Wood%20Duck%20q:A"])`
Hope this helps.

**Comment by mikful** [comment]
Great, got it to work, thanks for this.
