### ISSUE TITLE
downloads WAV files with MP3 extension

### ISSUE THREAD

**Issue by joshctaylor** [ntivirikin/xeno-canto-py#11]
All downloaded files appear to get a .mp3 filename regardless of their format. I've checked the media file headers, this example is for sure a WAV.

I download datasets for Southern Hairy-legged Myotis using:

`xeno-canto -dl Southern Hairy-legged Myotis`

which among others downloads the file:
`819608.mp3`

If I use the web api for the same file:
https://xeno-canto.org/838712/download

I get a file with the correct WAV extension.
XC819608 - Southern Hairy-legged Myotis - Myotis keaysi.wav

**Comment by ntivirikin** [comment]
Fix is in now, will update with new version when sono branch is finished development. Thank you!
