### ISSUE TITLE
correct syntax to pass a location to xenocanto.download?

### ISSUE THREAD

**Issue by zepadovani** [ntivirikin/xeno-canto-py#9]
Hi, 
when I have locations with more than one word, I'm not being successfull to pass them as  'params' to xenocanto.dowload.

For example... something like

    params = ["loc:Manhattan"]
    asyncio.run(xenocanto.download(filt=params))

works well.

But something like:
    params = ["loc:New", "York"]
    asyncio.run(xenocanto.download(filt=params))

does not. Have tried to change params to a single string "loc:New York", to ["loc:New York"], to ["loc:New\ York"], but all those options fail...

Any clues?

**Comment by zepadovani** [comment]
oh, sorry for the buzz....

it's: 
`params = ["loc:\"New York\""]`

thanks!

**Comment by harrisonford** [comment]
Unrelated but I was searching for a way to use the download function directly thanks!
